### ISSUE TITLE
Does `testcontainers` have to be a direct dependecy?

### ISSUE THREAD

**Issue by omBratteng** [cerbos/cerbos-sdk-python#21]
Does the dependency `testcontainers` need to be a direct dependency, or could it be moved to an optional dependency?

**Comment by charithe** [comment]
I suppose it can be an optional dependency. It's there to provide a way for users to easily launch Cerbos for tests so that's why we include it by default. We can try to move it behind "extras" but that would be a potential breaking change for existing users.

What's the reason you want to make it optional? Concerned about dependency bloat or something else?

**Comment by omBratteng** [comment]
Dependency bloat, but also that I now potentially have a docker client inside a deployment somewhere
